# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x0buserPackage\"*\n\x0bUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"7\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"\x17\n\tUserReqId\x12\n\n\x02id\x18\x01 \x01(\x05\"<\n\x10UserListResponse\x12(\n\x05users\x18\x01 \x03(\x0b\x32\x19.userPackage.UserResponse\"\x07\n\x05\x45mpty2\xc3\x02\n\x04User\x12>\n\tListUsers\x12\x12.userPackage.Empty\x1a\x1d.userPackage.UserListResponse\x12<\n\x07GetUser\x12\x16.userPackage.UserReqId\x1a\x19.userPackage.UserResponse\x12\x41\n\nCreateUser\x12\x18.userPackage.UserRequest\x1a\x19.userPackage.UserResponse\x12@\n\x08\x45\x64itUser\x12\x19.userPackage.UserResponse\x1a\x19.userPackage.UserResponse\x12\x38\n\nDeleteUser\x12\x16.userPackage.UserReqId\x1a\x12.userPackage.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREQUEST']._serialized_start=28
  _globals['_USERREQUEST']._serialized_end=70
  _globals['_USERRESPONSE']._serialized_start=72
  _globals['_USERRESPONSE']._serialized_end=127
  _globals['_USERREQID']._serialized_start=129
  _globals['_USERREQID']._serialized_end=152
  _globals['_USERLISTRESPONSE']._serialized_start=154
  _globals['_USERLISTRESPONSE']._serialized_end=214
  _globals['_EMPTY']._serialized_start=216
  _globals['_EMPTY']._serialized_end=223
  _globals['_USER']._serialized_start=226
  _globals['_USER']._serialized_end=549
# @@protoc_insertion_point(module_scope)
